// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-TJ3El5FPI5dIozNae_LlQQ5Amt3DyoA',
    appId: '1:402380573985:web:04f7b8ecf81147e6980260',
    messagingSenderId: '402380573985',
    projectId: 'docvault-8b0b1',
    authDomain: 'docvault-8b0b1.firebaseapp.com',
    storageBucket: 'docvault-8b0b1.firebasestorage.app',
    measurementId: 'G-XESLDX7HHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcfufRWkxvlrZv0XSb4bP1PoOi6FL_EEs',
    appId: '1:402380573985:android:117da7582a36edbe980260',
    messagingSenderId: '402380573985',
    projectId: 'docvault-8b0b1',
    storageBucket: 'docvault-8b0b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeM5Ra1unsW_JiqjBawtlJNtRt-2nu59c',
    appId: '1:402380573985:ios:377eaefddcfd17d1980260',
    messagingSenderId: '402380573985',
    projectId: 'docvault-8b0b1',
    storageBucket: 'docvault-8b0b1.firebasestorage.app',
    iosClientId: '402380573985-pd9eshrdt4qnuk1urmsskapopovm75k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.docvault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeM5Ra1unsW_JiqjBawtlJNtRt-2nu59c',
    appId: '1:402380573985:ios:377eaefddcfd17d1980260',
    messagingSenderId: '402380573985',
    projectId: 'docvault-8b0b1',
    storageBucket: 'docvault-8b0b1.firebasestorage.app',
    iosClientId: '402380573985-pd9eshrdt4qnuk1urmsskapopovm75k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.docvault',
  );

}